-- ============================================================
-- TOUR ATOMS — атомарная база компонентов туров
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tour_atoms (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  icon            TEXT DEFAULT '',
  category        TEXT NOT NULL,
  "group"         TEXT NOT NULL,
  duration_hours  INT,
  net             INT NOT NULL DEFAULT 0,
  sell            INT NOT NULL DEFAULT 0,
  mgr             INT NOT NULL DEFAULT 0,
  pricing_unit    TEXT NOT NULL DEFAULT 'per_pax',
  divisible       BOOLEAN NOT NULL DEFAULT false,
  tags            TEXT[] DEFAULT '{}',
  notes           TEXT DEFAULT '',
  active          BOOLEAN NOT NULL DEFAULT true,
  sort_order      INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_atoms_cat   ON public.tour_atoms(category);
CREATE INDEX IF NOT EXISTS idx_atoms_group ON public.tour_atoms("group");
CREATE INDEX IF NOT EXISTS idx_atoms_active ON public.tour_atoms(active);

ALTER TABLE public.tour_atoms ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "atoms_select" ON public.tour_atoms;
DROP POLICY IF EXISTS "atoms_insert" ON public.tour_atoms;
DROP POLICY IF EXISTS "atoms_update" ON public.tour_atoms;
DROP POLICY IF EXISTS "atoms_delete" ON public.tour_atoms;
CREATE POLICY "atoms_select" ON public.tour_atoms FOR SELECT TO authenticated USING (true);
CREATE POLICY "atoms_insert" ON public.tour_atoms FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "atoms_update" ON public.tour_atoms FOR UPDATE TO authenticated USING (true);
CREATE POLICY "atoms_delete" ON public.tour_atoms FOR DELETE TO authenticated USING (true);

-- SEED: 98 атомов с placeholder ценами
DELETE FROM public.tour_atoms WHERE id LIKE 'a%';  -- чистка старых seed-записей

INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a001', 'Минивэн 5ч (русский гид)', '🚐', 'transport', 'Транспорт', 5, 5000, 10000, 10000, 'per_vehicle', true, '{"phuket"}', 'Базовый пакет 5ч', true, 2) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a002', 'Минивэн 8ч (русский гид)', '🚐', 'transport', 'Транспорт', 8, 6000, 12000, 12000, 'per_vehicle', true, '{"phuket"}', 'Базовый пакет 8ч', true, 3) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a003', 'Минивэн 5ч + лонгтейл', '🚐', 'transport', 'Транспорт', 5, 8500, 13500, 13500, 'per_vehicle', true, '{}', '', true, 4) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a004', 'Минивэн 8ч + лонгтейл', '🚐', 'transport', 'Транспорт', 8, 9500, 15000, 15000, 'per_vehicle', true, '{}', '', true, 5) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a005', 'Альфард 5ч (русский гид)', '⭐', 'transport', 'Транспорт', 5, 10000, 20000, 20000, 'per_vehicle', true, '{}', '', true, 6) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a006', 'Альфард 8ч (русский гид)', '⭐', 'transport', 'Транспорт', 8, 11500, 22000, 22000, 'per_vehicle', true, '{}', '', true, 7) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a007', 'Альфард 5ч + лонгтейл', '⭐', 'transport', 'Транспорт', 5, 15000, 23500, 23500, 'per_vehicle', true, '{}', '', true, 8) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a008', 'Альфард 8ч + лонгтейл', '⭐', 'transport', 'Транспорт', 8, 15000, 25000, 25000, 'per_vehicle', true, '{}', '', true, 9) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a009', 'Лонгтейл 4ч (отдельно)', '⛵', 'transport', 'Транспорт', 4, 4000, 6000, 6000, 'per_vehicle', true, '{}', '', true, 10) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a010', 'Скоростная лодка 2 мотора', '🚤', 'transport', 'Транспорт', 8, 25000, 40000, 40000, 'per_vehicle', true, '{}', '', true, 11) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a011', 'Скоростная лодка 3 мотора', '🚤', 'transport', 'Транспорт', 8, 32000, 47000, 47000, 'per_vehicle', true, '{}', '', true, 12) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a012', 'Авиабилет Бангкок (туда-обратно)', '✈️', 'transport', 'Транспорт', NULL, 8000, 11000, 11000, 'per_pax', false, '{}', '', true, 13) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a013', 'Авиабилет Сингапур (туда-обратно)', '✈️', 'transport', 'Транспорт', NULL, 18000, 22800, 22800, 'per_pax', false, '{}', '', true, 14) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a014', 'Авиабилет Бали (туда-обратно)', '✈️', 'transport', 'Транспорт', NULL, 16000, 20000, 20000, 'per_pax', false, '{}', '', true, 15) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a015', 'Авиабилет Гонконг (туда-обратно)', '✈️', 'transport', 'Транспорт', NULL, 17000, 22000, 22000, 'per_pax', false, '{}', '', true, 16) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a016', 'Русский гид 5ч', '🗣', 'guide', 'Гид', 5, 1500, 2000, 2000, 'per_group_fixed', false, '{}', '', true, 17) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a017', 'Русский гид 8ч', '🗣', 'guide', 'Гид', 8, 2000, 2500, 2500, 'per_group_fixed', false, '{}', '', true, 18) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a018', 'Русский гид 2 дня', '🗣', 'guide', 'Гид', NULL, 4000, 5000, 5000, 'per_group_fixed', false, '{}', '', true, 19) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a019', 'Англоговорящий гид 8ч', '🗣', 'guide', 'Гид', 8, 1500, 2200, 2200, 'per_group_fixed', false, '{}', '', true, 20) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a020', 'Завтрак (буфет)', '🥐', 'meal', 'Питание', NULL, 250, 400, 400, 'per_pax', false, '{}', '', true, 21) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a021', 'Ланч-бокс из отеля', '🥪', 'meal', 'Питание', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Заказать на ресепшн до 17:00', true, 22) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a022', 'Обед стандарт', '🍜', 'meal', 'Питание', NULL, 200, 350, 350, 'per_pax', false, '{}', '', true, 23) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a023', 'Обед с морепродуктами', '🦐', 'meal', 'Питание', NULL, 350, 550, 550, 'per_pax', false, '{}', '', true, 24) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a024', 'Обед в плавучем ресторане', '🛶', 'meal', 'Питание', NULL, 250, 400, 400, 'per_pax', false, '{}', '', true, 25) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a025', 'Обед в цыганской деревне', '🍤', 'meal', 'Питание', NULL, 250, 350, 350, 'per_pax', false, '{}', '', true, 26) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a026', 'Обед на 76-м этаже Baiyoke', '🍽', 'meal', 'Питание', NULL, 600, 900, 900, 'per_pax', false, '{}', '', true, 27) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a027', 'Ужин стандарт', '🌙', 'meal', 'Питание', NULL, 250, 400, 400, 'per_pax', false, '{}', '', true, 28) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a028', 'Стеклянный мост Самет Нангше', '🌉', 'location', 'Локации Пхукет', NULL, 500, 800, 800, 'per_pax', false, '{}', '', true, 29) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a029', 'Стеклянный мост + завтрак', '🌅', 'location', 'Локации Пхукет', NULL, 600, 1000, 1000, 'per_pax', false, '{}', '', true, 30) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a030', 'Самет Нангше (без моста)', '⛰️', 'location', 'Локации Пхукет', NULL, 100, 300, 300, 'per_pax', false, '{}', '', true, 31) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a031', 'Большой Будда', '🛕', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Бесплатно', true, 32) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a032', 'Wat Chalong', '🛕', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Бесплатно', true, 33) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a033', 'Храм Суван Куха (обезьяны)', '🐒', 'location', 'Локации Пхукет', NULL, 20, 20, 20, 'per_pax', false, '{}', '', true, 34) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a034', 'Храм Ват Кана (Белый храм)', '⛩️', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 35) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a035', 'Храм Ва Пхра Тонг (закопанный Будда)', '🪙', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 36) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a036', 'Храм Ада и Рая', '🔥', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 37) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a037', 'Храм Чёрного Монаха', '🧘', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 38) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a038', 'Храм Ранг Хилл', '🛕', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 39) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a039', 'Karon Viewpoint (3 пляжа)', '🌊', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 40) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a040', 'Смотровая Ранг Хилл', '🦍', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Кормление обезьян', true, 41) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a041', 'Мыс Промтеп', '🌅', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 42) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a042', 'Ветряная мельница (смотровая)', '💨', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 43) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a043', 'Смотровая Као Кад 360°', '🔭', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 44) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a044', 'Пляж Майкао с самолётами', '✈️', 'location', 'Локации Пхукет', NULL, 40, 50, 50, 'per_pax', false, '{}', '', true, 45) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a045', 'Старый город Пхукет', '🏛', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 46) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a046', 'Улица Таланг Роуд', '🏘', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 47) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a047', 'Розовое кафе', '🌸', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 48) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a048', 'Кафе с кувшинками', '🪷', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Заказ напитка', true, 49) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a049', 'Видовое кафе на дереве', '☕', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 50) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a050', 'Деревня Каренов', '🪶', 'location', 'Локации Пхукет', NULL, 250, 500, 500, 'per_pax', false, '{}', '', true, 51) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a051', 'Плавучая деревня морских цыган', '🛟', 'location', 'Локации Пхукет', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 52) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a052', 'Деревня слонов (заповедник)', '🐘', 'location', 'Локации Пхукет', NULL, 250, 500, 500, 'per_pax', false, '{}', '', true, 53) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a053', 'Нацпарк о. Джеймса Бонда (вход)', '🪨', 'location', 'Локации Пхукет', NULL, 300, 300, 300, 'per_pax', false, '{}', '', true, 54) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a054', 'Озеро Чео Лан (нацпарк)', '🏞', 'location', 'Локации Краби и нацпарки', NULL, 100, 250, 250, 'per_pax', false, '{}', '', true, 55) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a055', 'Скалы Гуилинь', '🗿', 'location', 'Локации Краби и нацпарки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 56) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a056', 'Белый храм Краби', '⛩️', 'location', 'Локации Краби и нацпарки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 57) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a057', 'Храм Тигра (Wat Tham Suea)', '🐅', 'location', 'Локации Краби и нацпарки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 58) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a058', 'Горячие источники Краби', '♨️', 'location', 'Локации Краби и нацпарки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 59) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a059', 'Горячие источники Натай', '♨️', 'location', 'Локации Краби и нацпарки', NULL, 400, 500, 500, 'per_pax', false, '{}', '', true, 60) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a060', 'Купание со слоном (бассейн+душ)', '🐘', 'activity', 'Активности', NULL, 500, 1000, 1000, 'per_pax', false, '{}', '', true, 61) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a061', 'Купание со слоном (море+прогулка)', '🐘', 'activity', 'Активности', NULL, 500, 1000, 1000, 'per_pax', false, '{}', '', true, 62) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a062', 'Купание со слоном (полный пакет)', '🐘', 'activity', 'Активности', NULL, 1000, 1900, 1900, 'per_pax', false, '{}', '', true, 63) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a063', 'Шоу слонёнка', '🐘', 'activity', 'Активности', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Включено в Деревню слонов', true, 64) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a064', 'Катание на слонах', '🐘', 'activity', 'Активности', NULL, 200, 400, 400, 'per_pax', false, '{}', '', true, 65) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a065', 'Бамбуковые плоты по реке', '🎋', 'activity', 'Активности', NULL, 150, 500, 500, 'per_pax', false, '{}', '', true, 66) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a066', 'Каноэ', '🛶', 'activity', 'Активности', NULL, 150, 250, 250, 'per_pax', false, '{}', '', true, 67) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a067', 'Рафтинг 5км', '🚣', 'activity', 'Активности', NULL, 400, 700, 700, 'per_pax', false, '{}', '', true, 68) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a068', 'Тарзанка Flying Fox 200м', '🪂', 'activity', 'Активности', NULL, 300, 500, 500, 'per_pax', false, '{}', '', true, 69) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a069', 'Снорклинг (с пирса)', '🤿', 'activity', 'Активности', NULL, 200, 400, 400, 'per_pax', false, '{}', '', true, 70) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a070', 'Квадроциклы', '🏍', 'activity', 'Активности', NULL, 500, 1000, 1000, 'per_pax', false, '{}', '', true, 71) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a071', 'Сафари по озеру Чео Лан', '🦁', 'activity', 'Активности', NULL, 500, 800, 800, 'per_pax', false, '{}', '', true, 72) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a072', 'Mantra Spa (релакс-программа)', '💆', 'activity', 'Активности', NULL, 990, 1200, 1200, 'per_pax', false, '{}', '', true, 73) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a073', 'Змеиная ферма (шоу с кобрами)', '🐍', 'activity', 'Активности', NULL, 0, 0, 0, 'per_pax', false, '{}', 'Бесплатное посещение', true, 74) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a074', 'Парк Птиц (Phuket Bird Park)', '🦜', 'activity', 'Активности', NULL, 200, 400, 400, 'per_pax', false, '{}', '', true, 75) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a075', 'Крокодиловая ферма (шоу)', '🐊', 'activity', 'Активности', NULL, 100, 250, 250, 'per_pax', false, '{}', '', true, 76) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a076', 'Бунгало на воде Чео Лан (1 ночь, 2-местное)', '🛖', 'stay', 'Проживание', NULL, 1500, 2500, 2500, 'per_pax', false, '{}', '', true, 77) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a077', 'Домик в нацпарке (1 ночь)', '🏕', 'stay', 'Проживание', NULL, 1200, 2000, 2000, 'per_pax', false, '{}', '', true, 78) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a078', 'Стандартная гостиница (1 ночь)', '🏨', 'stay', 'Проживание', NULL, 1500, 2500, 2500, 'per_pax', false, '{}', '', true, 79) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a079', 'Доплата за одноместное размещение', '🛏', 'stay', 'Проживание', NULL, 1000, 1500, 1500, 'per_group_fixed', false, '{}', '', true, 80) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a080', 'Депозит за шкафчик в спа', '🔐', 'stay', 'Проживание', NULL, 100, 100, 100, 'per_pax', false, '{}', 'Возвращается', true, 81) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a081', 'Royal Shark (центр)', '🦈', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 82) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a082', 'Princess Jewerly Phuket', '💎', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 83) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a083', 'Латексная фабрика', '🛏', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 84) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a084', 'Фабрика орехов кешью', '🥜', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 85) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a085', 'Жемчужная ферма', '🦪', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 86) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a086', 'ТЦ Central Festival', '🛍', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 87) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a087', 'Royal Aptek Moringa', '💊', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 88) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a088', 'Galleria Самоцветов', '💍', 'shopping', 'Шоппинг', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 89) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a089', 'Friday Avenue Market (Пятница)', '🌃', 'evening', 'Вечерние рынки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 90) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a090', 'Naka Weekend Market (Суббота)', '🌃', 'evening', 'Вечерние рынки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 91) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a091', 'Aптека Ривер Квай', '🌿', 'evening', 'Вечерние рынки', NULL, 0, 0, 0, 'per_pax', false, '{}', '', true, 92) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a092', 'Индивидуальный трансфер из Као Лак', '🚐', 'extra', 'Доплаты', NULL, 3000, 4000, 4000, 'per_group_fixed', false, '{}', 'За машину туда-обратно', true, 93) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a093', 'Индивидуальный трансфер из Натай', '🚐', 'extra', 'Доплаты', NULL, 4000, 5500, 5500, 'per_group_fixed', false, '{}', '', true, 94) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a094', 'Дальние районы (Ао По, Сирей)', '🗺', 'extra', 'Доплаты', NULL, 2000, 2500, 2500, 'per_group_fixed', false, '{}', '', true, 95) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a095', 'Доплата за праздничные даты', '🎉', 'extra', 'Доплаты', NULL, 1500, 2000, 2000, 'per_group_fixed', false, '{}', '1-5 января', true, 96) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a096', 'Доплата за багаж', '🧳', 'extra', 'Доплаты', NULL, 400, 500, 500, 'per_group_fixed', false, '{}', '', true, 97) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a097', 'Виза Сингапур (если требуется)', '🛂', 'extra', 'Доплаты', NULL, 2000, 3000, 3000, 'per_pax', false, '{}', '', true, 98) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();
INSERT INTO public.tour_atoms (id, name, icon, category, "group", duration_hours, net, sell, mgr, pricing_unit, divisible, tags, notes, active, sort_order) VALUES ('a098', 'Аренда удочки', '🎣', 'extra', 'Доплаты', NULL, 300, 500, 500, 'per_pax', false, '{}', '', true, 99) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, sell=EXCLUDED.sell, net=EXCLUDED.net, mgr=EXCLUDED.mgr, updated_at=NOW();

-- ATOMIC TOURS — таблица для собранных атомных туров
CREATE TABLE IF NOT EXISTS public.atomic_tours (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_name     TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'draft',
  pax             JSONB NOT NULL DEFAULT '{"adults":2,"children":0,"infants":0}',
  mode            TEXT NOT NULL DEFAULT 'group',
  selected        JSONB NOT NULL DEFAULT '[]',
  total_sell      INT NOT NULL DEFAULT 0,
  total_net       INT NOT NULL DEFAULT 0,
  total_margin    INT NOT NULL DEFAULT 0,
  notes           TEXT NOT NULL DEFAULT '',
  metadata        JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_atom_tours_creator ON public.atomic_tours(created_by);
ALTER TABLE public.atomic_tours ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "at_select" ON public.atomic_tours;
DROP POLICY IF EXISTS "at_insert" ON public.atomic_tours;
DROP POLICY IF EXISTS "at_update" ON public.atomic_tours;
DROP POLICY IF EXISTS "at_delete" ON public.atomic_tours;
CREATE POLICY "at_select" ON public.atomic_tours FOR SELECT TO authenticated
  USING (created_by = auth.uid() OR EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'booking'));
CREATE POLICY "at_insert" ON public.atomic_tours FOR INSERT TO authenticated WITH CHECK (created_by = auth.uid());
CREATE POLICY "at_update" ON public.atomic_tours FOR UPDATE TO authenticated
  USING (created_by = auth.uid() OR EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'booking'));
CREATE POLICY "at_delete" ON public.atomic_tours FOR DELETE TO authenticated
  USING (created_by = auth.uid() OR EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'booking'));


SELECT 'Atoms: ' || COUNT(*) || ' rows' FROM public.tour_atoms;